GET http://localhost:5000/

###
POST http://localhost:5000/sessions
Content-Type: application/json

{
    "users": [
        {
            "name": "Alice",
            "password": "123"
        },
        {
            "name": "Bob",
            "password": "456"
        }
    ],
    "services": [
        {
            "name": "Service1"
        },
        {
            "name": "Service2"
        }
    ],
    "permissions": [
        {
            "users": ["Alice"],
            "service": "Service1"
        },
        {
            "users": ["Bob"],
            "service": "Service2"
        }
    ]
}

###
POST http://localhost:5000/sessions/1/users/logIn
Content-Type: application/json

{
    "username": "viet"
}

###
POST http://localhost:5000/sessions/1/services/1/authorize
Content-Type: application/json

{
    "message": {
        "tgt": "bauz%%GxAfuOSJIyjhBvEQ%%0984176060687",
        "service_id": 1
    },
    "authenticator": "kiqt%%4473346088316"
}

###
POST http://localhost:5000/sessions/1/services/23/handshake
Content-Type: application/json

{
    "client_to_server_ticket": "kueq%%7770351473278%%pJdZcVLZKgsaieci",
    "authenticator": "egii%%7905100368338"
}